### ISSUE TITLE
'Settings' object has no attribute 'TEMPLATE_STRING_IF_INVALID'

### ISSUE THREAD

**Issue by bracki** [phrase/django-phrase#10]
`TEMPLATE_STRING_IF_INVALID` has been deprecated as of Django 1.8.
It is being used [here](https://github.com/phrase/django-phrase/blob/master/phrase/nodes.py#L62).
That means when loading the phrase plugin in a template that uses `blocktrans`
newer versions of Django will now crash. Details on how to upgrade can be found [here](https://docs.djangoproject.com/en/1.11/ref/templates/upgrading/#upgrading-templates-to-django-1-8).

**Comment by sacry-dyn** [comment]
Hi @bracki thank you for telling us. We will look into it an come back with a solution.

**Comment by sacry-dyn** [comment]
We opened a PR for this. Could you review? https://github.com/phrase/django-phrase/pull/11
