### ISSUE TITLE
Two import errors

### ISSUE THREAD

**Issue by iceripple** [phrase/django-phrase#2]
After installing phrase I get two errors:

1: ImportError raised loading phrase.templatetags.phrase_i18n: cannot import name render_value_in_context

in nodes.py importing render_value_in_context fails because  (in django 1.4) this method name starts with an underscore.
so:
from django.template.base import render_value_in_context
should be:
from django.template.base import _render_value_in_context as render_value_in_context

2: File "..phrase/templatetags/phrase_i18n.py", line 67, in top
   m = re.match("^'([^']+)'(\|.*$)", value)

NameError: global name 're' is not defined
(running python 2.7)
obviously to be solved by adding "import re" in phrase_i18n.py

**Comment by docstun** [comment]
Finally fixed in #3.
