### ISSUE TITLE
Phrase In-Context not working for Django 4

### ISSUE THREAD

**Issue by sifat-cefalo** [phrase/django-phrase#22]
my requirements.txt
asgiref==3.5.0
backports.zoneinfo==0.2.1
Django==4.0.4
django-phrase==1.0.8
six==1.16.0
sqlparse==0.4.2

After following the readme.md tutorial, phrase footerbar is showing, but editor not working. No translation is showing as key.

**Comment by sifat-cefalo** [comment]
seems like {% translate %} tag is not supported by django-phrase for django 4

**Comment by theSoenke** [comment]
@sifat-cefalo thanks for reporting this. We're looking into this to add support for Django 4

**Comment by strzibny** [comment]
@sifat-cefalo I tried to support Django 4 in https://github.com/phrase/django-phrase/pull/23. Would you be so kind and try it out that it works for you?

**Comment by strzibny** [comment]
Fixed in #23 and released as `1.1.0` https://pypi.org/project/django-phrase/1.1.0/
