### ISSUE TITLE
Template Tag {% blocktrans %} results in AttributeError or TemplateSyntaxError

### ISSUE THREAD

**Issue by A070B24C** [phrase/django-phrase#8]
After installing, adding and configuring **`django-phrase`** in our project I discovered a problem with the **`blocktrans`** template tag. There are two different errors:

1. Just **`blocktrans`** tag
2. The **`blocktrans`** tag with argument **`trimmed`**

To provoke the described bugs install [django-demo-application](https://github.com/phrase/django-demo-application) and change line **`<h1>{% trans 'ThisIsH1' %}</h1>`** within **polls/template/index.html** to raise appropriate bug/problem.

1. Just **blocktrans** tag 
**`<h1>`**
**`{% blocktrans %}`**
**`  ThisIsH1.`**
**`  Or at least,`**
**`  should be!`**
**`{% endblocktrans %}`**
**`</h1>`**

**Results in:
AttributeError at /polls/
'unicode' object has no attribute 'literal'**

2. The **blocktrans** tag with argument **trimmed**
**`<h1>`**
**`{% blocktrans trimmed %}`**
**`  ThisIsH1.`**
**`  Or at least,`**
**`  should be!`**
**`{% endblocktrans %}`**
**`</h1>`**

**Results in:
TemplateSyntaxError at /polls/
Unknown argument for u'blocktrans' tag: u'trimmed'.**

Both versions of code work if you disable
**`{% load phrase_i18n %}`**
**`{% phrase_javascript %}`**
within above mentioned **`index.html`** file.  For more information see attached Traceback files.

[20170315_PhraseApp Bug Blocktrans Trimmed.txt](https://github.com/phrase/django-phrase/files/844734/20170315_PhraseApp.Bug.Blocktrans.Trimmed.txt)
[20170315_PhraseApp Bug Blocktrans.txt](https://github.com/phrase/django-phrase/files/844735/20170315_PhraseApp.Bug.Blocktrans.txt)

**Comment by sacry-dyn** [comment]
Hi @otoprak thank you for reaching out and sorry for the late reply. We will look into this and come back to you with a solution or possible fix.

**Comment by otoprak** [comment]
Alo @sacry-dyn sacry-dyn, no worries and thank you guys in advance.

**Comment by sacry-dyn** [comment]
Hey @otoprak can you git clone and checkout this branch https://github.com/phrase/django-phrase/tree/unicode-literal-fix and do

`$ pip install -e ./path_to/django-phrase`

The problem is that for some reason the variable is not a Django Variable but a unicode string in which case there is no `.literal` method defined on it. Anyway we are on it, just as a quick fix and if we are running in the right direction.

**Comment by otoprak** [comment]
Thanks for the fast reply. Tried out your fix branch and I guess you are in the right direction :)

Without the "trimmed" argument it at least does not through an error. The term within the blocktrans block gets wrapped by the phraseapp prefix and suffix, but can't be translated anyway.

The behaviour with the "trimmed" argument is the same: through former described error.

**Comment by sacry-dyn** [comment]
@otoprak what do you mean by "can't be translated anyway"? 

With the following the trimmed argument should be passed: 

https://github.com/phrase/django-phrase/tree/unicode-literal-fix

**Comment by otoprak** [comment]
@sacry-dyn @otoprak what do you mean by "can't be translated anyway"?
Just to be proper: This comment is meant for the commit
c0f0ce496561f21a9ae07056841223181abdf674

Just made a screenshot - hope that it explains it a bit better:

![20170403_phraseapp_after_unicode_fix](https://cloud.githubusercontent.com/assets/15701564/24629562/bb491512-18b9-11e7-8307-8cb05ab62e43.png)

To double check it, I even generated a new token. 

Code itself:
```
    <h1>
    {% blocktrans %}
        ThisIsH1
    {% endblocktrans %}
    </h1>
```

**Comment by sacry-dyn** [comment]
@A070B24C so, the problem is that blocktrans does not strip the content in the h1 tag. The problem then is there is a space between the key and the phrase tag. We will now always strip on the name to properly support this. Can you verify that this works for you?

https://github.com/phrase/django-phrase/pull/9

**Comment by A070B24C** [comment]
Latest commit seems to fix the "blocktrans" and "blocktrans trimmed" bug.

Unfortunately I accidentally discovered another bug:
Every "%" gets doubled within an "blocktrans" block. With and without trimmed.

```
    <h1>
    {% blocktrans %}
        ThisIs 100% H1
    {% endblocktrans %}
    </h1>
```

Outputs:
```
ThisIs 100%% H1
```

**Comment by sacry-dyn** [comment]
Hey @A070B24C , sorry for letting you wait on this. We had public holiday in Germany and things are little delayed. We will look into it and fix it (hopefully for good) :).

**Comment by sacry-dyn** [comment]
@A070B24C we replaced the % in normal text tokens with %% as an escaping strategy. In that context it might not make that much sense. 

https://github.com/phrase/django-phrase/pull/9/commits/b173517a93c17e1131385ad7a657c47d673a26e6

If this resolves your issue I would merge the PR.

**Comment by A070B24C** [comment]
Alo @sacry-dyn no worries, same here in Switzerland ;)

I just checked out the latest changes and now everything works flawless: good job!

And by accident I stumbled over this today: 
https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#troubleshooting-ugettext-incorrectly-detects-python-format-in-strings-with-percent-signs

**Comment by sacry-dyn** [comment]
@A070B24C thank you for the source. We will merge this for now (as I couldn't find a way to provoke the specified error). If something comes up we will expand on this (for now this should work).
